### ISSUE TITLE
Проблемы

### ISSUE THREAD

**Issue by JuneYoonSam** [MjKey/DonatonTimer#1]
Увы, как бы не старался таймер в самом обс стоит на 00:00:00
Менял порты и т.п., не помогает, в чем может быть проблема?

**Comment by JuneYoonSam** [comment]
![image](https://github.com/user-attachments/assets/b0a92519-ba05-4593-b7a9-2bd8b7179fd0)

**Comment by MjKey** [comment]
Возможно проблема была с локальным IP
На всякий случай попробуйте следующие действия:

Запустить от имени администратора
Отключить брадмауер или антивирус
Обновить кеш страницы в свойствах источника браузера в OBS

Если выше не помогло или вы уже пробовали все эти действия
Попробуйте этот фикс - [Lastest](https://github.com/MjKey/DonatonTimer/actions/runs/10296934260) - [Download Artifacts](https://github.com/MjKey/DonatonTimer/actions/runs/10296934260/artifacts/1788994360)

**Comment by JuneYoonSam** [comment]
Благодарствую, фикшенная версия сразу отобразила таймер в обс.

**Comment by MjKey** [comment]
Fixed in [2.0.3](https://github.com/MjKey/DonatonTimer/releases/tag/2.0.3)
